// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/homepage/BoldPremium.tsx": () => import("../components/mockups/homepage/BoldPremium.tsx"),
  "./components/mockups/homepage/CleanMinimal.tsx": () => import("../components/mockups/homepage/CleanMinimal.tsx")
};
